#!/bin/bash

suffix=$((1 + RANDOM % 100000))
repo_name="x_axisname_y_yaxisname_reponame_$suffix"
mkdir $PWD/$repo_name

#make sub repos
mkdir $PWD/$repo_name/raw
mkdir $PWD/$repo_name/excel
mkdir $PWD/$repo_name/scripts
mkdir $PWD/$repo_name/graphs
